apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: kubeflow
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: the-testing-key
            operator: In
            values:
            - the-testing-val1
        - matchExpressions:
          - key: the-testing-key2
            operator: In
            values:
            - the-testing-val2
  containers:
  - image: nginx:1.14.2
    name: nginx
    ports:
    - containerPort: 80
